name: Savior
version: '${project.version}'
main: de.tdf.savior.Savior
api-version: 1.19
authors: [ TearsDontFall ]
description: Survival Plugin


commands:
  SetLanguage:
    description: Set your preferred language.